#' timeavestats
#'
#' Evaluates confidence intervals around time-averaging statistics
#' using resampling methods that incrporate dating uncertainty.
#' Accepts object of the class 'postidst' generated by function postdist.
#'
#' @details To be developed.
#'
#'
#' @param age A numerical vector containing age values to which probabilities are assigned
#'
#' @param prob A numerical vector containing probabilities for each age value
#'

#'
#' @return A list with the following items:
#'   \item{spec}{returns specimen-level estimates of mean age, age variance,
#'   and median age based on Monte Carlo sample from posterior age distributions
#'   and "exact" mean ages, age variances, and median ages calculated directly
#'   from posterior probabilities; see details}
#'   \item{sample}{returns a numerical vector with sample-level estimates of
#'   central tendency, dispersion, and skewness; see details}
#'   \item{outdata}{returns a numerical matrix with n='size' rows and n=number of specimens
#'   columns with Monte Carlo ages based on posterior probability distributions.
#'   NOTE: returned when outdata = TRUE}
#'
#' @examples
#'
#' postdist(age=bahamas$post$Age, prob=bahamas$post$Probability,
#' id=bahamas$post$Specimen, idname='Specimen')
#'
#' @importFrom lmom samlmu
#'
#' @export
#'
#' @references Hosking, JRM, 2023, L-Moments. R package, version 3.0.
#' https://CRAN.R-project.org/package=lmom
#'
#' Ritter, M, Erthal F, Kosnik, MA, Kowalewski, M, Coimbra, CJ,
#' Caron, F, Kaufman, DS, 2023, Onshore-offshore trends in the temporal
#' resolution of molluscan death assemblages: how age-frequency
#' distributions reveal Quaternary sea-level history.
#' Palaios, 38: 148-157. http://dx.doi.org/10.2110/palo.2021.041
#'

timeavestats <- function(x, times=100) {
  if (!('postdist' %in% class(x))) stop('object of the class "postdist" is required')
 if (length(x)==2) stop('"outdata" is missing: re-run "postdist" with outdata=TRUE')
  reps <- nrow(x$outdata)
  sampleF <- function(x) x[runif(1, 1, reps)]
  out1 <- NULL
  for (i in 1:times) {
    rsam <- apply(x$outdata, 2, sampleF)
    out1 <- rbind(out1, rsam)
  }
  return(out1)
}
